// AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Run `dart run ffigen --config ffigen.yaml` to regenerate.
// ignore_for_file: type=lint, unused_element, camel_case_types, non_constant_identifier_names
// ignore_for_file: unnecessary_import, prefer_final_fields, unused_import
// ignore_for_file: unused_field, duplicate_ignore

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

/// Auto-generated bindings for dart_vips C wrappers. DO NOT EDIT BY HAND.
class LibVipsOps {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LibVipsOps(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LibVipsOps.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void dart_g_free(ffi.Pointer<ffi.Void> mem) {
    return _dart_g_free(mem);
  }

  late final _dart_g_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'dart_g_free',
      );
  late final _dart_g_free = _dart_g_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void dart_g_object_ref(ffi.Pointer<VipsImage> obj) {
    return _dart_g_object_ref(obj);
  }

  late final _dart_g_object_refPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VipsImage>)>>(
        'dart_g_object_ref',
      );
  late final _dart_g_object_ref = _dart_g_object_refPtr
      .asFunction<void Function(ffi.Pointer<VipsImage>)>();

  void dart_g_object_unref(ffi.Pointer<VipsImage> obj) {
    return _dart_g_object_unref(obj);
  }

  late final _dart_g_object_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VipsImage>)>>(
        'dart_g_object_unref',
      );
  late final _dart_g_object_unref = _dart_g_object_unrefPtr
      .asFunction<void Function(ffi.Pointer<VipsImage>)>();

  int dart_vips_autorot(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
  ) {
    return _dart_vips_autorot(in$, out);
  }

  late final _dart_vips_autorotPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
          )
        >
      >('dart_vips_autorot');
  late final _dart_vips_autorot = _dart_vips_autorotPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
        )
      >();

  int dart_vips_colourspace(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    VipsInterpretation space,
  ) {
    return _dart_vips_colourspace(in$, out, space.value);
  }

  late final _dart_vips_colourspacePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Int,
          )
        >
      >('dart_vips_colourspace');
  late final _dart_vips_colourspace = _dart_vips_colourspacePtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          int,
        )
      >();

  int dart_vips_composite2(
    ffi.Pointer<VipsImage> base,
    ffi.Pointer<VipsImage> overlay,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    VipsBlendMode mode,
    int x,
    int y,
  ) {
    return _dart_vips_composite2(base, overlay, out, mode.value, x, y);
  }

  late final _dart_vips_composite2Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.UnsignedInt,
            ffi.Int,
            ffi.Int,
          )
        >
      >('dart_vips_composite2');
  late final _dart_vips_composite2 = _dart_vips_composite2Ptr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          int,
          int,
          int,
        )
      >();

  int dart_vips_crop(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    int left,
    int top,
    int width,
    int height,
  ) {
    return _dart_vips_crop(in$, out, left, top, width, height);
  }

  late final _dart_vips_cropPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('dart_vips_crop');
  late final _dart_vips_crop = _dart_vips_cropPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          int,
          int,
          int,
          int,
        )
      >();

  int dart_vips_embed(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    int x,
    int y,
    int width,
    int height,
    VipsExtend extend,
  ) {
    return _dart_vips_embed(in$, out, x, y, width, height, extend.value);
  }

  late final _dart_vips_embedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.UnsignedInt,
          )
        >
      >('dart_vips_embed');
  late final _dart_vips_embed = _dart_vips_embedPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          int,
          int,
          int,
          int,
          int,
        )
      >();

  int dart_vips_flatten(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    double bg_r,
    double bg_g,
    double bg_b,
  ) {
    return _dart_vips_flatten(in$, out, bg_r, bg_g, bg_b);
  }

  late final _dart_vips_flattenPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Double,
            ffi.Double,
            ffi.Double,
          )
        >
      >('dart_vips_flatten');
  late final _dart_vips_flatten = _dart_vips_flattenPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          double,
          double,
          double,
        )
      >();

  int dart_vips_flip(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    VipsDirection direction,
  ) {
    return _dart_vips_flip(in$, out, direction.value);
  }

  late final _dart_vips_flipPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.UnsignedInt,
          )
        >
      >('dart_vips_flip');
  late final _dart_vips_flip = _dart_vips_flipPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          int,
        )
      >();

  int dart_vips_icc_transform(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    ffi.Pointer<ffi.Char> output_profile,
  ) {
    return _dart_vips_icc_transform(in$, out, output_profile);
  }

  late final _dart_vips_icc_transformPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('dart_vips_icc_transform');
  late final _dart_vips_icc_transform = _dart_vips_icc_transformPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<VipsImage> dart_vips_image_from_buffer(
    ffi.Pointer<ffi.Void> buf,
    int len,
  ) {
    return _dart_vips_image_from_buffer(buf, len);
  }

  late final _dart_vips_image_from_bufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VipsImage> Function(ffi.Pointer<ffi.Void>, ffi.Size)
        >
      >('dart_vips_image_from_buffer');
  late final _dart_vips_image_from_buffer = _dart_vips_image_from_bufferPtr
      .asFunction<
        ffi.Pointer<VipsImage> Function(ffi.Pointer<ffi.Void>, int)
      >();

  int dart_vips_image_get_double(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Double> out,
  ) {
    return _dart_vips_image_get_double(in$, name, out);
  }

  late final _dart_vips_image_get_doublePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Double>,
          )
        >
      >('dart_vips_image_get_double');
  late final _dart_vips_image_get_double = _dart_vips_image_get_doublePtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Double>,
        )
      >();

  ffi.Pointer<ffi.Pointer<ffi.Char>> dart_vips_image_get_fields(
    ffi.Pointer<VipsImage> in$,
  ) {
    return _dart_vips_image_get_fields(in$);
  }

  late final _dart_vips_image_get_fieldsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<VipsImage>)
        >
      >('dart_vips_image_get_fields');
  late final _dart_vips_image_get_fields = _dart_vips_image_get_fieldsPtr
      .asFunction<
        ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<VipsImage>)
      >();

  int dart_vips_image_get_int(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Int> out,
  ) {
    return _dart_vips_image_get_int(in$, name, out);
  }

  late final _dart_vips_image_get_intPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('dart_vips_image_get_int');
  late final _dart_vips_image_get_int = _dart_vips_image_get_intPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  int dart_vips_image_get_string(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out,
  ) {
    return _dart_vips_image_get_string(in$, name, out);
  }

  late final _dart_vips_image_get_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('dart_vips_image_get_string');
  late final _dart_vips_image_get_string = _dart_vips_image_get_stringPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  ffi.Pointer<VipsImage> dart_vips_image_new_from_file(
    ffi.Pointer<ffi.Char> path,
  ) {
    return _dart_vips_image_new_from_file(path);
  }

  late final _dart_vips_image_new_from_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VipsImage> Function(ffi.Pointer<ffi.Char>)
        >
      >('dart_vips_image_new_from_file');
  late final _dart_vips_image_new_from_file = _dart_vips_image_new_from_filePtr
      .asFunction<ffi.Pointer<VipsImage> Function(ffi.Pointer<ffi.Char>)>();

  int dart_vips_image_remove(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _dart_vips_image_remove(in$, name);
  }

  late final _dart_vips_image_removePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<VipsImage>, ffi.Pointer<ffi.Char>)
        >
      >('dart_vips_image_remove');
  late final _dart_vips_image_remove = _dart_vips_image_removePtr
      .asFunction<
        int Function(ffi.Pointer<VipsImage>, ffi.Pointer<ffi.Char>)
      >();

  void dart_vips_image_set_double(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Char> name,
    double value,
  ) {
    return _dart_vips_image_set_double(in$, name, value);
  }

  late final _dart_vips_image_set_doublePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Char>,
            ffi.Double,
          )
        >
      >('dart_vips_image_set_double');
  late final _dart_vips_image_set_double = _dart_vips_image_set_doublePtr
      .asFunction<
        void Function(ffi.Pointer<VipsImage>, ffi.Pointer<ffi.Char>, double)
      >();

  void dart_vips_image_set_int(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Char> name,
    int value,
  ) {
    return _dart_vips_image_set_int(in$, name, value);
  }

  late final _dart_vips_image_set_intPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('dart_vips_image_set_int');
  late final _dart_vips_image_set_int = _dart_vips_image_set_intPtr
      .asFunction<
        void Function(ffi.Pointer<VipsImage>, ffi.Pointer<ffi.Char>, int)
      >();

  void dart_vips_image_set_string(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> str,
  ) {
    return _dart_vips_image_set_string(in$, name, str);
  }

  late final _dart_vips_image_set_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('dart_vips_image_set_string');
  late final _dart_vips_image_set_string = _dart_vips_image_set_stringPtr
      .asFunction<
        void Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int dart_vips_image_to_buffer(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Char> suffix,
    ffi.Pointer<ffi.Pointer<ffi.Void>> buf,
    ffi.Pointer<ffi.Size> len,
  ) {
    return _dart_vips_image_to_buffer(in$, suffix, buf, len);
  }

  late final _dart_vips_image_to_bufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('dart_vips_image_to_buffer');
  late final _dart_vips_image_to_buffer = _dart_vips_image_to_bufferPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int dart_vips_image_write_to_file(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _dart_vips_image_write_to_file(in$, path);
  }

  late final _dart_vips_image_write_to_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<VipsImage>, ffi.Pointer<ffi.Char>)
        >
      >('dart_vips_image_write_to_file');
  late final _dart_vips_image_write_to_file = _dart_vips_image_write_to_filePtr
      .asFunction<
        int Function(ffi.Pointer<VipsImage>, ffi.Pointer<ffi.Char>)
      >();

  int dart_vips_reduce(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    double hshrink,
    double vshrink,
  ) {
    return _dart_vips_reduce(in$, out, hshrink, vshrink);
  }

  late final _dart_vips_reducePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Double,
            ffi.Double,
          )
        >
      >('dart_vips_reduce');
  late final _dart_vips_reduce = _dart_vips_reducePtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          double,
          double,
        )
      >();

  int dart_vips_resize(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    double hscale,
    double vscale,
  ) {
    return _dart_vips_resize(in$, out, hscale, vscale);
  }

  late final _dart_vips_resizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Double,
            ffi.Double,
          )
        >
      >('dart_vips_resize');
  late final _dart_vips_resize = _dart_vips_resizePtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          double,
          double,
        )
      >();

  int dart_vips_rot(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    VipsAngle angle,
  ) {
    return _dart_vips_rot(in$, out, angle.value);
  }

  late final _dart_vips_rotPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.UnsignedInt,
          )
        >
      >('dart_vips_rot');
  late final _dart_vips_rot = _dart_vips_rotPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          int,
        )
      >();

  int dart_vips_similarity(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    double angle,
  ) {
    return _dart_vips_similarity(in$, out, angle);
  }

  late final _dart_vips_similarityPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Double,
          )
        >
      >('dart_vips_similarity');
  late final _dart_vips_similarity = _dart_vips_similarityPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          double,
        )
      >();

  int dart_vips_smartcrop(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    int width,
    int height,
    VipsInteresting interesting,
  ) {
    return _dart_vips_smartcrop(in$, out, width, height, interesting.value);
  }

  late final _dart_vips_smartcropPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Int,
            ffi.Int,
            ffi.UnsignedInt,
          )
        >
      >('dart_vips_smartcrop');
  late final _dart_vips_smartcrop = _dart_vips_smartcropPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          int,
          int,
          int,
        )
      >();

  int dart_vips_thumbnail(
    ffi.Pointer<VipsImage> in$,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    int width,
    int height,
    VipsInteresting crop,
  ) {
    return _dart_vips_thumbnail(in$, out, width, height, crop.value);
  }

  late final _dart_vips_thumbnailPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<VipsImage>,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Int,
            ffi.Int,
            ffi.UnsignedInt,
          )
        >
      >('dart_vips_thumbnail');
  late final _dart_vips_thumbnail = _dart_vips_thumbnailPtr
      .asFunction<
        int Function(
          ffi.Pointer<VipsImage>,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          int,
          int,
          int,
        )
      >();

  int dart_vips_thumbnail_buffer(
    ffi.Pointer<ffi.Void> buf,
    int len,
    ffi.Pointer<ffi.Pointer<VipsImage>> out,
    int width,
    int height,
    VipsInteresting crop,
  ) {
    return _dart_vips_thumbnail_buffer(
      buf,
      len,
      out,
      width,
      height,
      crop.value,
    );
  }

  late final _dart_vips_thumbnail_bufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<VipsImage>>,
            ffi.Int,
            ffi.Int,
            ffi.UnsignedInt,
          )
        >
      >('dart_vips_thumbnail_buffer');
  late final _dart_vips_thumbnail_buffer = _dart_vips_thumbnail_bufferPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.Pointer<VipsImage>>,
          int,
          int,
          int,
        )
      >();

  void dart_vips_unref_void(ffi.Pointer<ffi.Void> obj) {
    return _dart_vips_unref_void(obj);
  }

  late final _dart_vips_unref_voidPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'dart_vips_unref_void',
      );
  late final _dart_vips_unref_void = _dart_vips_unref_voidPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Char> vips_error_buffer() {
    return _vips_error_buffer();
  }

  late final _vips_error_bufferPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'vips_error_buffer',
      );
  late final _vips_error_buffer = _vips_error_bufferPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  void vips_error_clear() {
    return _vips_error_clear();
  }

  late final _vips_error_clearPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('vips_error_clear');
  late final _vips_error_clear = _vips_error_clearPtr
      .asFunction<void Function()>();

  int vips_init(ffi.Pointer<ffi.Char> argv0) {
    return _vips_init(argv0);
  }

  late final _vips_initPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'vips_init',
      );
  late final _vips_init = _vips_initPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  void vips_shutdown() {
    return _vips_shutdown();
  }

  late final _vips_shutdownPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('vips_shutdown');
  late final _vips_shutdown = _vips_shutdownPtr.asFunction<void Function()>();

  int vips_version(int flag) {
    return _vips_version(flag);
  }

  late final _vips_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('vips_version');
  late final _vips_version = _vips_versionPtr.asFunction<int Function(int)>();
}

typedef GByteArray = _GByteArray;
typedef GData = _GData;
typedef GHashTable = _GHashTable;
typedef GMutex = _GMutex;
typedef GObject = _GObject;
typedef GObjectClass = _GObjectClass;
typedef GObjectConstructParam = _GObjectConstructParam;

/// GParamFlags:
/// @G_PARAM_READABLE: the parameter is readable
/// @G_PARAM_WRITABLE: the parameter is writable
/// @G_PARAM_READWRITE: alias for %G_PARAM_READABLE | %G_PARAM_WRITABLE
/// @G_PARAM_CONSTRUCT: the parameter will be set upon object construction.
/// See [vfunc@Object.constructed] for more details
/// @G_PARAM_CONSTRUCT_ONLY: the parameter can only be set upon object construction.
/// See [vfunc@Object.constructed] for more details
/// @G_PARAM_LAX_VALIDATION: upon parameter conversion (see g_param_value_convert())
/// strict validation is not required
/// @G_PARAM_STATIC_NAME: the string used as name when constructing the
/// parameter is guaranteed to remain valid and
/// unmodified for the lifetime of the parameter.
/// Since 2.8
/// @G_PARAM_STATIC_NICK: the string used as nick when constructing the
/// parameter is guaranteed to remain valid and
/// unmmodified for the lifetime of the parameter.
/// Since 2.8
/// @G_PARAM_STATIC_BLURB: the string used as blurb when constructing the
/// parameter is guaranteed to remain valid and
/// unmodified for the lifetime of the parameter.
/// Since 2.8
/// @G_PARAM_EXPLICIT_NOTIFY: calls to g_object_set_property() for this
/// property will not automatically result in a "notify" signal being
/// emitted: the implementation must call g_object_notify() themselves
/// in case the property actually changes.  Since: 2.42.
/// @G_PARAM_PRIVATE: internal
/// @G_PARAM_DEPRECATED: the parameter is deprecated and will be removed
/// in a future version. A warning will be generated if it is used
/// while running with G_ENABLE_DIAGNOSTIC=1.
/// Since 2.26
///
/// Through the #GParamFlags flag values, certain aspects of parameters
/// can be configured.
///
/// See also: %G_PARAM_STATIC_STRINGS
sealed class GParamFlags {
  static const G_PARAM_READABLE = 1;
  static const G_PARAM_WRITABLE = 2;
  static const G_PARAM_READWRITE = 3;
  static const G_PARAM_CONSTRUCT = 4;
  static const G_PARAM_CONSTRUCT_ONLY = 8;
  static const G_PARAM_LAX_VALIDATION = 16;
  static const G_PARAM_STATIC_NAME = 32;
  static const G_PARAM_PRIVATE = 32;
  static const G_PARAM_STATIC_NICK = 64;
  static const G_PARAM_STATIC_BLURB = 128;
  static const G_PARAM_EXPLICIT_NOTIFY = 1073741824;
  static const G_PARAM_DEPRECATED = -2147483648;
}

typedef GParamSpec = _GParamSpec;
typedef GSList = _GSList;
typedef GSList$1 = _GSList;
typedef GThread = _GThread;
typedef GThreadFunc = ffi.Pointer<ffi.NativeFunction<GThreadFuncFunction>>;
typedef GThreadFuncFunction = gpointer Function(gpointer data);

enum GThreadPriority {
  G_THREAD_PRIORITY_LOW(0),
  G_THREAD_PRIORITY_NORMAL(1),
  G_THREAD_PRIORITY_HIGH(2),
  G_THREAD_PRIORITY_URGENT(3);

  final int value;
  const GThreadPriority(this.value);

  static GThreadPriority fromValue(int value) => switch (value) {
    0 => G_THREAD_PRIORITY_LOW,
    1 => G_THREAD_PRIORITY_NORMAL,
    2 => G_THREAD_PRIORITY_HIGH,
    3 => G_THREAD_PRIORITY_URGENT,
    _ => throw ArgumentError('Unknown value for GThreadPriority: $value'),
  };
}

typedef GTimer = _GTimer;
typedef GType = gsize;
typedef GTypeClass = _GTypeClass;
typedef GTypeInstance = _GTypeInstance;
typedef GValue = _GValue;

final class UnnamedUnion extends ffi.Union {
  @gint()
  external int v_int;

  @guint()
  external int v_uint;

  @glong()
  external int v_long;

  @gulong()
  external int v_ulong;

  @gint64()
  external int v_int64;

  @guint64()
  external int v_uint64;

  @gfloat()
  external double v_float;

  @gdouble()
  external double v_double;

  external gpointer v_pointer;
}

const int VIPS_ARGUMENT_OPTIONAL_INPUT = 18;

const int VIPS_ARGUMENT_OPTIONAL_OUTPUT = 34;

const int VIPS_ARGUMENT_REQUIRED_INPUT = 19;

const int VIPS_ARGUMENT_REQUIRED_OUTPUT = 35;

const double VIPS_A_X0 = 109.8503;

const double VIPS_A_Y0 = 100.0;

const double VIPS_A_Z0 = 35.5849;

const double VIPS_B_X0 = 99.072;

const double VIPS_B_Y0 = 100.0;

const double VIPS_B_Z0 = 85.223;

const String VIPS_CONFIG =
    'enable debug: false\nenable deprecated: true\nenable modules: true\nenable C++ binding: true\nenable RAD load/save: true\nenable Analyze7 load: true\nenable PPM load/save: true\nenable GIF load: true\nFFTs with fftw3: true\nSIMD support with libhwy: true\nICC profile support with lcms2: true\ndeflate compression with zlib: true\ntext rendering with pangocairo: true\nfont file support with fontconfig: true\nEXIF metadata support with libexif: true\nJPEG load/save with libjpeg: true\nUHDR load/save with libuhdr: true\nJXL load/save with libjxl: true (dynamic module: true)\nJPEG2000 load/save with libopenjp2: true\nPNG load/save with libpng: true\nimage quantisation with imagequant: true\nTIFF load/save with libtiff-4: true\nimage pyramid save with libarchive: true\nHEIC/AVIF load/save with libheif: true (dynamic module: true)\nWebP load/save with libwebp: true\nPDF load with poppler-glib: true (dynamic module: true)\nSVG load with librsvg-2.0: true\nEXR load with OpenEXR: true\nWSI load with openslide: true (dynamic module: true)\nMatlab load with matio: true\nNIfTI load/save with libnifti: false\nFITS load/save with cfitsio: true\nGIF save with cgif: true\nRAW load with libraw_r: true\nMagick load/save with MagickCore: true (dynamic module: true)';

const double VIPS_C_X0 = 98.07;

const double VIPS_C_Y0 = 100.0;

const double VIPS_C_Z0 = 118.23;

const double VIPS_D3250_X0 = 105.659;

const double VIPS_D3250_Y0 = 100.0;

const double VIPS_D3250_Z0 = 45.8501;

const double VIPS_D50_X0 = 96.425;

const double VIPS_D50_Y0 = 100.0;

const double VIPS_D50_Z0 = 82.468;

const double VIPS_D55_X0 = 95.6831;

const double VIPS_D55_Y0 = 100.0;

const double VIPS_D55_Z0 = 92.0871;

const double VIPS_D65_X0 = 95.047;

const double VIPS_D65_Y0 = 100.0;

const double VIPS_D65_Z0 = 108.8827;

const double VIPS_D75_X0 = 94.9682;

const double VIPS_D75_Y0 = 100.0;

const double VIPS_D75_Z0 = 122.571;

const double VIPS_D93_X0 = 89.74;

const double VIPS_D93_Y0 = 100.0;

const double VIPS_D93_Z0 = 130.77;

const int VIPS_DEFAULT_MAX_COORD = 100000000;

const int VIPS_ENABLE_DEPRECATED = 1;

const double VIPS_E_X0 = 100.0;

const double VIPS_E_Y0 = 100.0;

const double VIPS_E_Z0 = 100.0;

const int VIPS_LIBRARY_AGE = 20;

const int VIPS_LIBRARY_CURRENT = 62;

const int VIPS_LIBRARY_REVISION = 3;

const int VIPS_MAGIC_INTEL = 3064394248;

const int VIPS_MAGIC_SPARC = 150120118;

const int VIPS_MAJOR_VERSION = 8;

const int VIPS_MICRO_VERSION = 3;

const int VIPS_MINOR_VERSION = 18;

const String VIPS_VERSION = '8.18.3';

const String VIPS_VERSION_STRING = '8.18.3';

enum VipsAccess {
  VIPS_ACCESS_RANDOM(0),
  VIPS_ACCESS_SEQUENTIAL(1),
  VIPS_ACCESS_SEQUENTIAL_UNBUFFERED(2),
  VIPS_ACCESS_LAST(3);

  final int value;
  const VipsAccess(this.value);

  static VipsAccess fromValue(int value) => switch (value) {
    0 => VIPS_ACCESS_RANDOM,
    1 => VIPS_ACCESS_SEQUENTIAL,
    2 => VIPS_ACCESS_SEQUENTIAL_UNBUFFERED,
    3 => VIPS_ACCESS_LAST,
    _ => throw ArgumentError('Unknown value for VipsAccess: $value'),
  };
}

enum VipsAngle {
  VIPS_ANGLE_D0(0),
  VIPS_ANGLE_D90(1),
  VIPS_ANGLE_D180(2),
  VIPS_ANGLE_D270(3),
  VIPS_ANGLE_LAST(4);

  final int value;
  const VipsAngle(this.value);

  static VipsAngle fromValue(int value) => switch (value) {
    0 => VIPS_ANGLE_D0,
    1 => VIPS_ANGLE_D90,
    2 => VIPS_ANGLE_D180,
    3 => VIPS_ANGLE_D270,
    4 => VIPS_ANGLE_LAST,
    _ => throw ArgumentError('Unknown value for VipsAngle: $value'),
  };
}

typedef VipsArea = _VipsArea;
typedef VipsArgument = _VipsArgument;
typedef VipsArgumentClass = _VipsArgumentClass;
typedef VipsArgumentClassMapFn =
    ffi.Pointer<ffi.NativeFunction<VipsArgumentClassMapFnFunction>>;
typedef VipsArgumentClassMapFnFunction =
    ffi.Pointer<ffi.Void> Function(
      ffi.Pointer<VipsObjectClass> object_class,
      ffi.Pointer<GParamSpec> pspec,
      ffi.Pointer<VipsArgumentClass> argument_class,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
    );

enum VipsArgumentFlags {
  VIPS_ARGUMENT_NONE(0),
  VIPS_ARGUMENT_REQUIRED(1),
  VIPS_ARGUMENT_CONSTRUCT(2),
  VIPS_ARGUMENT_SET_ONCE(4),
  VIPS_ARGUMENT_SET_ALWAYS(8),
  VIPS_ARGUMENT_INPUT(16),
  VIPS_ARGUMENT_OUTPUT(32),
  VIPS_ARGUMENT_DEPRECATED(64),
  VIPS_ARGUMENT_MODIFY(128),
  VIPS_ARGUMENT_NON_HASHABLE(256);

  final int value;
  const VipsArgumentFlags(this.value);

  static VipsArgumentFlags fromValue(int value) => switch (value) {
    0 => VIPS_ARGUMENT_NONE,
    1 => VIPS_ARGUMENT_REQUIRED,
    2 => VIPS_ARGUMENT_CONSTRUCT,
    4 => VIPS_ARGUMENT_SET_ONCE,
    8 => VIPS_ARGUMENT_SET_ALWAYS,
    16 => VIPS_ARGUMENT_INPUT,
    32 => VIPS_ARGUMENT_OUTPUT,
    64 => VIPS_ARGUMENT_DEPRECATED,
    128 => VIPS_ARGUMENT_MODIFY,
    256 => VIPS_ARGUMENT_NON_HASHABLE,
    _ => throw ArgumentError('Unknown value for VipsArgumentFlags: $value'),
  };
}

typedef VipsArgumentInstance = _VipsArgumentInstance;
typedef VipsArgumentMapFn =
    ffi.Pointer<ffi.NativeFunction<VipsArgumentMapFnFunction>>;
typedef VipsArgumentMapFnFunction =
    ffi.Pointer<ffi.Void> Function(
      ffi.Pointer<VipsObject> object,
      ffi.Pointer<GParamSpec> pspec,
      ffi.Pointer<VipsArgumentClass> argument_class,
      ffi.Pointer<VipsArgumentInstance> argument_instance,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
    );
typedef VipsArgumentTable = GHashTable;
typedef VipsArrayDouble = _VipsArrayDouble;
typedef VipsArrayImage = _VipsArrayImage;
typedef VipsArrayInt = _VipsArrayInt;

enum VipsBandFormat {
  VIPS_FORMAT_NOTSET(-1),
  VIPS_FORMAT_UCHAR(0),
  VIPS_FORMAT_CHAR(1),
  VIPS_FORMAT_USHORT(2),
  VIPS_FORMAT_SHORT(3),
  VIPS_FORMAT_UINT(4),
  VIPS_FORMAT_INT(5),
  VIPS_FORMAT_FLOAT(6),
  VIPS_FORMAT_COMPLEX(7),
  VIPS_FORMAT_DOUBLE(8),
  VIPS_FORMAT_DPCOMPLEX(9),
  VIPS_FORMAT_LAST(10);

  final int value;
  const VipsBandFormat(this.value);

  static VipsBandFormat fromValue(int value) => switch (value) {
    -1 => VIPS_FORMAT_NOTSET,
    0 => VIPS_FORMAT_UCHAR,
    1 => VIPS_FORMAT_CHAR,
    2 => VIPS_FORMAT_USHORT,
    3 => VIPS_FORMAT_SHORT,
    4 => VIPS_FORMAT_UINT,
    5 => VIPS_FORMAT_INT,
    6 => VIPS_FORMAT_FLOAT,
    7 => VIPS_FORMAT_COMPLEX,
    8 => VIPS_FORMAT_DOUBLE,
    9 => VIPS_FORMAT_DPCOMPLEX,
    10 => VIPS_FORMAT_LAST,
    _ => throw ArgumentError('Unknown value for VipsBandFormat: $value'),
  };
}

enum VipsBlendMode {
  VIPS_BLEND_MODE_CLEAR(0),
  VIPS_BLEND_MODE_SOURCE(1),
  VIPS_BLEND_MODE_OVER(2),
  VIPS_BLEND_MODE_IN(3),
  VIPS_BLEND_MODE_OUT(4),
  VIPS_BLEND_MODE_ATOP(5),
  VIPS_BLEND_MODE_DEST(6),
  VIPS_BLEND_MODE_DEST_OVER(7),
  VIPS_BLEND_MODE_DEST_IN(8),
  VIPS_BLEND_MODE_DEST_OUT(9),
  VIPS_BLEND_MODE_DEST_ATOP(10),
  VIPS_BLEND_MODE_XOR(11),
  VIPS_BLEND_MODE_ADD(12),
  VIPS_BLEND_MODE_SATURATE(13),
  VIPS_BLEND_MODE_MULTIPLY(14),
  VIPS_BLEND_MODE_SCREEN(15),
  VIPS_BLEND_MODE_OVERLAY(16),
  VIPS_BLEND_MODE_DARKEN(17),
  VIPS_BLEND_MODE_LIGHTEN(18),
  VIPS_BLEND_MODE_COLOUR_DODGE(19),
  VIPS_BLEND_MODE_COLOUR_BURN(20),
  VIPS_BLEND_MODE_HARD_LIGHT(21),
  VIPS_BLEND_MODE_SOFT_LIGHT(22),
  VIPS_BLEND_MODE_DIFFERENCE(23),
  VIPS_BLEND_MODE_EXCLUSION(24),
  VIPS_BLEND_MODE_LAST(25);

  final int value;
  const VipsBlendMode(this.value);

  static VipsBlendMode fromValue(int value) => switch (value) {
    0 => VIPS_BLEND_MODE_CLEAR,
    1 => VIPS_BLEND_MODE_SOURCE,
    2 => VIPS_BLEND_MODE_OVER,
    3 => VIPS_BLEND_MODE_IN,
    4 => VIPS_BLEND_MODE_OUT,
    5 => VIPS_BLEND_MODE_ATOP,
    6 => VIPS_BLEND_MODE_DEST,
    7 => VIPS_BLEND_MODE_DEST_OVER,
    8 => VIPS_BLEND_MODE_DEST_IN,
    9 => VIPS_BLEND_MODE_DEST_OUT,
    10 => VIPS_BLEND_MODE_DEST_ATOP,
    11 => VIPS_BLEND_MODE_XOR,
    12 => VIPS_BLEND_MODE_ADD,
    13 => VIPS_BLEND_MODE_SATURATE,
    14 => VIPS_BLEND_MODE_MULTIPLY,
    15 => VIPS_BLEND_MODE_SCREEN,
    16 => VIPS_BLEND_MODE_OVERLAY,
    17 => VIPS_BLEND_MODE_DARKEN,
    18 => VIPS_BLEND_MODE_LIGHTEN,
    19 => VIPS_BLEND_MODE_COLOUR_DODGE,
    20 => VIPS_BLEND_MODE_COLOUR_BURN,
    21 => VIPS_BLEND_MODE_HARD_LIGHT,
    22 => VIPS_BLEND_MODE_SOFT_LIGHT,
    23 => VIPS_BLEND_MODE_DIFFERENCE,
    24 => VIPS_BLEND_MODE_EXCLUSION,
    25 => VIPS_BLEND_MODE_LAST,
    _ => throw ArgumentError('Unknown value for VipsBlendMode: $value'),
  };
}

typedef VipsBlob = _VipsBlob;
typedef VipsBuf = _VipsBuf;
typedef VipsBuffer = _VipsBuffer;
typedef VipsBufferCache = _VipsBufferCache;

final class VipsBufferThread extends ffi.Struct {
  external ffi.Pointer<GHashTable> hash;

  external ffi.Pointer<GThread> thread;
}

typedef VipsCallbackFn =
    ffi.Pointer<ffi.NativeFunction<VipsCallbackFnFunction>>;
typedef VipsCallbackFnFunction =
    ffi.Int Function(ffi.Pointer<ffi.Void> a, ffi.Pointer<ffi.Void> b);
typedef DartVipsCallbackFnFunction =
    int Function(ffi.Pointer<ffi.Void> a, ffi.Pointer<ffi.Void> b);
typedef VipsClassMapFn =
    ffi.Pointer<ffi.NativeFunction<VipsClassMapFnFunction>>;
typedef VipsClassMapFnFunction =
    ffi.Pointer<ffi.Void> Function(
      ffi.Pointer<VipsObjectClass> cls,
      ffi.Pointer<ffi.Void> a,
    );

enum VipsCoding {
  VIPS_CODING_ERROR(-1),
  VIPS_CODING_NONE(0),
  VIPS_CODING_LABQ(2),
  VIPS_CODING_RAD(6),
  VIPS_CODING_LAST(7);

  final int value;
  const VipsCoding(this.value);

  static VipsCoding fromValue(int value) => switch (value) {
    -1 => VIPS_CODING_ERROR,
    0 => VIPS_CODING_NONE,
    2 => VIPS_CODING_LABQ,
    6 => VIPS_CODING_RAD,
    7 => VIPS_CODING_LAST,
    _ => throw ArgumentError('Unknown value for VipsCoding: $value'),
  };
}

typedef VipsConnection = _VipsConnection;

enum VipsDemandStyle {
  VIPS_DEMAND_STYLE_ERROR(-1),
  VIPS_DEMAND_STYLE_SMALLTILE(0),
  VIPS_DEMAND_STYLE_FATSTRIP(1),
  VIPS_DEMAND_STYLE_THINSTRIP(2),
  VIPS_DEMAND_STYLE_ANY(3);

  final int value;
  const VipsDemandStyle(this.value);

  static VipsDemandStyle fromValue(int value) => switch (value) {
    -1 => VIPS_DEMAND_STYLE_ERROR,
    0 => VIPS_DEMAND_STYLE_SMALLTILE,
    1 => VIPS_DEMAND_STYLE_FATSTRIP,
    2 => VIPS_DEMAND_STYLE_THINSTRIP,
    3 => VIPS_DEMAND_STYLE_ANY,
    _ => throw ArgumentError('Unknown value for VipsDemandStyle: $value'),
  };
}

enum VipsDirection {
  VIPS_DIRECTION_HORIZONTAL(0),
  VIPS_DIRECTION_VERTICAL(1),
  VIPS_DIRECTION_LAST(2);

  final int value;
  const VipsDirection(this.value);

  static VipsDirection fromValue(int value) => switch (value) {
    0 => VIPS_DIRECTION_HORIZONTAL,
    1 => VIPS_DIRECTION_VERTICAL,
    2 => VIPS_DIRECTION_LAST,
    _ => throw ArgumentError('Unknown value for VipsDirection: $value'),
  };
}

enum VipsExtend {
  VIPS_EXTEND_BLACK(0),
  VIPS_EXTEND_COPY(1),
  VIPS_EXTEND_REPEAT(2),
  VIPS_EXTEND_MIRROR(3),
  VIPS_EXTEND_WHITE(4),
  VIPS_EXTEND_BACKGROUND(5),
  VIPS_EXTEND_LAST(6);

  final int value;
  const VipsExtend(this.value);

  static VipsExtend fromValue(int value) => switch (value) {
    0 => VIPS_EXTEND_BLACK,
    1 => VIPS_EXTEND_COPY,
    2 => VIPS_EXTEND_REPEAT,
    3 => VIPS_EXTEND_MIRROR,
    4 => VIPS_EXTEND_WHITE,
    5 => VIPS_EXTEND_BACKGROUND,
    6 => VIPS_EXTEND_LAST,
    _ => throw ArgumentError('Unknown value for VipsExtend: $value'),
  };
}

/// VipsFailOn:
/// @VIPS_FAIL_ON_NONE: never stop
/// @VIPS_FAIL_ON_TRUNCATED: stop on image truncated, nothing else
/// @VIPS_FAIL_ON_ERROR: stop on serious error or truncation
/// @VIPS_FAIL_ON_WARNING: stop on anything, even warnings
///
/// How sensitive loaders are to errors, from never stop (very insensitive), to
/// stop on the smallest warning (very sensitive).
///
/// Each one implies the ones before it, so [enum@Vips.FailOn.ERROR] implies
/// [enum@Vips.FailOn.TRUNCATED].
enum VipsFailOn {
  VIPS_FAIL_ON_NONE(0),
  VIPS_FAIL_ON_TRUNCATED(1),
  VIPS_FAIL_ON_ERROR(2),
  VIPS_FAIL_ON_WARNING(3),
  VIPS_FAIL_ON_LAST(4);

  final int value;
  const VipsFailOn(this.value);

  static VipsFailOn fromValue(int value) => switch (value) {
    0 => VIPS_FAIL_ON_NONE,
    1 => VIPS_FAIL_ON_TRUNCATED,
    2 => VIPS_FAIL_ON_ERROR,
    3 => VIPS_FAIL_ON_WARNING,
    4 => VIPS_FAIL_ON_LAST,
    _ => throw ArgumentError('Unknown value for VipsFailOn: $value'),
  };
}

typedef VipsForeign = _VipsForeign;
typedef VipsForeignClass = _VipsForeignClass;

/// VipsForeignCoding:
/// @VIPS_FOREIGN_CODING_NONE: saver supports [enum@Vips.Coding.NONE]
/// @VIPS_FOREIGN_CODING_LABQ: saver supports [enum@Vips.Coding.LABQ]
/// @VIPS_FOREIGN_CODING_RAD: saver supports [enum@Vips.Coding.RAD]
/// @VIPS_FOREIGN_CODING_ALL: saver supports all coding types
///
/// The set of coding types supported by a saver.
///
/// ::: seealso
/// [enum@Coding].
enum VipsForeignCoding {
  VIPS_FOREIGN_CODING_NONE(1),
  VIPS_FOREIGN_CODING_LABQ(2),
  VIPS_FOREIGN_CODING_RAD(4),
  VIPS_FOREIGN_CODING_ALL(7);

  final int value;
  const VipsForeignCoding(this.value);

  static VipsForeignCoding fromValue(int value) => switch (value) {
    1 => VIPS_FOREIGN_CODING_NONE,
    2 => VIPS_FOREIGN_CODING_LABQ,
    4 => VIPS_FOREIGN_CODING_RAD,
    7 => VIPS_FOREIGN_CODING_ALL,
    _ => throw ArgumentError('Unknown value for VipsForeignCoding: $value'),
  };
}

enum VipsForeignFlags {
  VIPS_FOREIGN_NONE(0),
  VIPS_FOREIGN_PARTIAL(1),
  VIPS_FOREIGN_BIGENDIAN(2),
  VIPS_FOREIGN_SEQUENTIAL(4),
  VIPS_FOREIGN_ALL(7);

  final int value;
  const VipsForeignFlags(this.value);

  static VipsForeignFlags fromValue(int value) => switch (value) {
    0 => VIPS_FOREIGN_NONE,
    1 => VIPS_FOREIGN_PARTIAL,
    2 => VIPS_FOREIGN_BIGENDIAN,
    4 => VIPS_FOREIGN_SEQUENTIAL,
    7 => VIPS_FOREIGN_ALL,
    _ => throw ArgumentError('Unknown value for VipsForeignFlags: $value'),
  };
}

/// VipsForeignKeep:
/// @VIPS_FOREIGN_KEEP_NONE: don't attach metadata
/// @VIPS_FOREIGN_KEEP_EXIF: keep Exif metadata
/// @VIPS_FOREIGN_KEEP_XMP: keep XMP metadata
/// @VIPS_FOREIGN_KEEP_IPTC: keep IPTC metadata
/// @VIPS_FOREIGN_KEEP_ICC: keep ICC metadata
/// @VIPS_FOREIGN_KEEP_OTHER: keep other metadata (e.g. PNG comments)
/// @VIPS_FOREIGN_KEEP_GAINMAP: keep the gainmap metadata
/// @VIPS_FOREIGN_KEEP_ALL: keep all metadata
///
/// Which metadata to retain.
enum VipsForeignKeep {
  VIPS_FOREIGN_KEEP_NONE(0),
  VIPS_FOREIGN_KEEP_EXIF(1),
  VIPS_FOREIGN_KEEP_XMP(2),
  VIPS_FOREIGN_KEEP_IPTC(4),
  VIPS_FOREIGN_KEEP_ICC(8),
  VIPS_FOREIGN_KEEP_OTHER(16),
  VIPS_FOREIGN_KEEP_GAINMAP(32),
  VIPS_FOREIGN_KEEP_ALL(63);

  final int value;
  const VipsForeignKeep(this.value);

  static VipsForeignKeep fromValue(int value) => switch (value) {
    0 => VIPS_FOREIGN_KEEP_NONE,
    1 => VIPS_FOREIGN_KEEP_EXIF,
    2 => VIPS_FOREIGN_KEEP_XMP,
    4 => VIPS_FOREIGN_KEEP_IPTC,
    8 => VIPS_FOREIGN_KEEP_ICC,
    16 => VIPS_FOREIGN_KEEP_OTHER,
    32 => VIPS_FOREIGN_KEEP_GAINMAP,
    63 => VIPS_FOREIGN_KEEP_ALL,
    _ => throw ArgumentError('Unknown value for VipsForeignKeep: $value'),
  };
}

typedef VipsForeignLoad = _VipsForeignLoad;
typedef VipsForeignLoadClass = _VipsForeignLoadClass;
typedef VipsForeignSave = _VipsForeignSave;
typedef VipsForeignSaveClass = _VipsForeignSaveClass;

/// VipsForeignSaveable:
/// @VIPS_FOREIGN_SAVEABLE_ANY: saver supports everything (eg. TIFF)
/// @VIPS_FOREIGN_SAVEABLE_MONO: 1 band
/// @VIPS_FOREIGN_SAVEABLE_RGB: 3 bands
/// @VIPS_FOREIGN_SAVEABLE_CMYK: 4 bands
/// @VIPS_FOREIGN_SAVEABLE_ALPHA: an extra band
///
/// The set of image types supported by a saver.
///
/// ::: seealso
/// [class@ForeignSave].
enum VipsForeignSaveable {
  VIPS_FOREIGN_SAVEABLE_ANY(0),
  VIPS_FOREIGN_SAVEABLE_MONO(1),
  VIPS_FOREIGN_SAVEABLE_RGB(2),
  VIPS_FOREIGN_SAVEABLE_CMYK(4),
  VIPS_FOREIGN_SAVEABLE_ALPHA(8),
  VIPS_FOREIGN_SAVEABLE_ALL(15);

  final int value;
  const VipsForeignSaveable(this.value);

  static VipsForeignSaveable fromValue(int value) => switch (value) {
    0 => VIPS_FOREIGN_SAVEABLE_ANY,
    1 => VIPS_FOREIGN_SAVEABLE_MONO,
    2 => VIPS_FOREIGN_SAVEABLE_RGB,
    4 => VIPS_FOREIGN_SAVEABLE_CMYK,
    8 => VIPS_FOREIGN_SAVEABLE_ALPHA,
    15 => VIPS_FOREIGN_SAVEABLE_ALL,
    _ => throw ArgumentError('Unknown value for VipsForeignSaveable: $value'),
  };
}

typedef VipsGenerateFn =
    ffi.Pointer<ffi.NativeFunction<VipsGenerateFnFunction>>;
typedef VipsGenerateFnFunction =
    ffi.Int Function(
      ffi.Pointer<VipsRegion> out,
      ffi.Pointer<ffi.Void> seq,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
      ffi.Pointer<gboolean> stop,
    );
typedef DartVipsGenerateFnFunction =
    int Function(
      ffi.Pointer<VipsRegion> out,
      ffi.Pointer<ffi.Void> seq,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
      ffi.Pointer<gboolean> stop,
    );
typedef VipsImage = _VipsImage;
typedef VipsImage$1 = _VipsImage;
typedef VipsImageClass = _VipsImageClass;

enum VipsImageType {
  VIPS_IMAGE_ERROR(-1),
  VIPS_IMAGE_NONE(0),
  VIPS_IMAGE_SETBUF(1),
  VIPS_IMAGE_SETBUF_FOREIGN(2),
  VIPS_IMAGE_OPENIN(3),
  VIPS_IMAGE_MMAPIN(4),
  VIPS_IMAGE_MMAPINRW(5),
  VIPS_IMAGE_OPENOUT(6),
  VIPS_IMAGE_PARTIAL(7);

  final int value;
  const VipsImageType(this.value);

  static VipsImageType fromValue(int value) => switch (value) {
    -1 => VIPS_IMAGE_ERROR,
    0 => VIPS_IMAGE_NONE,
    1 => VIPS_IMAGE_SETBUF,
    2 => VIPS_IMAGE_SETBUF_FOREIGN,
    3 => VIPS_IMAGE_OPENIN,
    4 => VIPS_IMAGE_MMAPIN,
    5 => VIPS_IMAGE_MMAPINRW,
    6 => VIPS_IMAGE_OPENOUT,
    7 => VIPS_IMAGE_PARTIAL,
    _ => throw ArgumentError('Unknown value for VipsImageType: $value'),
  };
}

enum VipsInteresting {
  VIPS_INTERESTING_NONE(0),
  VIPS_INTERESTING_CENTRE(1),
  VIPS_INTERESTING_ENTROPY(2),
  VIPS_INTERESTING_ATTENTION(3),
  VIPS_INTERESTING_LOW(4),
  VIPS_INTERESTING_HIGH(5),
  VIPS_INTERESTING_ALL(6),
  VIPS_INTERESTING_LAST(7);

  final int value;
  const VipsInteresting(this.value);

  static VipsInteresting fromValue(int value) => switch (value) {
    0 => VIPS_INTERESTING_NONE,
    1 => VIPS_INTERESTING_CENTRE,
    2 => VIPS_INTERESTING_ENTROPY,
    3 => VIPS_INTERESTING_ATTENTION,
    4 => VIPS_INTERESTING_LOW,
    5 => VIPS_INTERESTING_HIGH,
    6 => VIPS_INTERESTING_ALL,
    7 => VIPS_INTERESTING_LAST,
    _ => throw ArgumentError('Unknown value for VipsInteresting: $value'),
  };
}

enum VipsInterpretation {
  VIPS_INTERPRETATION_ERROR(-1),
  VIPS_INTERPRETATION_MULTIBAND(0),
  VIPS_INTERPRETATION_B_W(1),
  VIPS_INTERPRETATION_HISTOGRAM(10),
  VIPS_INTERPRETATION_XYZ(12),
  VIPS_INTERPRETATION_LAB(13),
  VIPS_INTERPRETATION_CMYK(15),
  VIPS_INTERPRETATION_LABQ(16),
  VIPS_INTERPRETATION_RGB(17),
  VIPS_INTERPRETATION_CMC(18),
  VIPS_INTERPRETATION_LCH(19),
  VIPS_INTERPRETATION_LABS(21),
  VIPS_INTERPRETATION_sRGB(22),
  VIPS_INTERPRETATION_YXY(23),
  VIPS_INTERPRETATION_FOURIER(24),
  VIPS_INTERPRETATION_RGB16(25),
  VIPS_INTERPRETATION_GREY16(26),
  VIPS_INTERPRETATION_MATRIX(27),
  VIPS_INTERPRETATION_scRGB(28),
  VIPS_INTERPRETATION_HSV(29),
  VIPS_INTERPRETATION_OKLAB(30),
  VIPS_INTERPRETATION_OKLCH(31),
  VIPS_INTERPRETATION_LAST(32);

  final int value;
  const VipsInterpretation(this.value);

  static VipsInterpretation fromValue(int value) => switch (value) {
    -1 => VIPS_INTERPRETATION_ERROR,
    0 => VIPS_INTERPRETATION_MULTIBAND,
    1 => VIPS_INTERPRETATION_B_W,
    10 => VIPS_INTERPRETATION_HISTOGRAM,
    12 => VIPS_INTERPRETATION_XYZ,
    13 => VIPS_INTERPRETATION_LAB,
    15 => VIPS_INTERPRETATION_CMYK,
    16 => VIPS_INTERPRETATION_LABQ,
    17 => VIPS_INTERPRETATION_RGB,
    18 => VIPS_INTERPRETATION_CMC,
    19 => VIPS_INTERPRETATION_LCH,
    21 => VIPS_INTERPRETATION_LABS,
    22 => VIPS_INTERPRETATION_sRGB,
    23 => VIPS_INTERPRETATION_YXY,
    24 => VIPS_INTERPRETATION_FOURIER,
    25 => VIPS_INTERPRETATION_RGB16,
    26 => VIPS_INTERPRETATION_GREY16,
    27 => VIPS_INTERPRETATION_MATRIX,
    28 => VIPS_INTERPRETATION_scRGB,
    29 => VIPS_INTERPRETATION_HSV,
    30 => VIPS_INTERPRETATION_OKLAB,
    31 => VIPS_INTERPRETATION_OKLCH,
    32 => VIPS_INTERPRETATION_LAST,
    _ => throw ArgumentError('Unknown value for VipsInterpretation: $value'),
  };
}

typedef VipsObject = _VipsObject;
typedef VipsObjectClass = _VipsObjectClass;
typedef VipsObjectSetArguments =
    ffi.Pointer<ffi.NativeFunction<VipsObjectSetArgumentsFunction>>;
typedef VipsObjectSetArgumentsFunction =
    ffi.Pointer<ffi.Void> Function(
      ffi.Pointer<VipsObject> object,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
    );
typedef VipsOperation = _VipsOperation;
typedef VipsOperationClass = _VipsOperationClass;

enum VipsOperationFlags {
  VIPS_OPERATION_NONE(0),
  VIPS_OPERATION_SEQUENTIAL(1),
  VIPS_OPERATION_SEQUENTIAL_UNBUFFERED(2),
  VIPS_OPERATION_NOCACHE(4),
  VIPS_OPERATION_DEPRECATED(8),
  VIPS_OPERATION_UNTRUSTED(16),
  VIPS_OPERATION_BLOCKED(32),
  VIPS_OPERATION_REVALIDATE(64);

  final int value;
  const VipsOperationFlags(this.value);

  static VipsOperationFlags fromValue(int value) => switch (value) {
    0 => VIPS_OPERATION_NONE,
    1 => VIPS_OPERATION_SEQUENTIAL,
    2 => VIPS_OPERATION_SEQUENTIAL_UNBUFFERED,
    4 => VIPS_OPERATION_NOCACHE,
    8 => VIPS_OPERATION_DEPRECATED,
    16 => VIPS_OPERATION_UNTRUSTED,
    32 => VIPS_OPERATION_BLOCKED,
    64 => VIPS_OPERATION_REVALIDATE,
    _ => throw ArgumentError('Unknown value for VipsOperationFlags: $value'),
  };
}

/// VipsPel:
///
/// A picture element. Cast this to whatever the associated VipsBandFormat says
/// to get the value.
typedef VipsPel = ffi.UnsignedChar;
typedef DartVipsPel = int;
typedef VipsProgress = _VipsProgress;
typedef VipsRect = _VipsRect;
typedef VipsRefString = _VipsRefString;
typedef VipsRegion = _VipsRegion;
typedef VipsSaveString = _VipsSaveString;
typedef VipsSource = _VipsSource;
typedef VipsStartFn = ffi.Pointer<ffi.NativeFunction<VipsStartFnFunction>>;
typedef VipsStartFn$1 = ffi.Pointer<ffi.NativeFunction<VipsStartFnFunction$1>>;
typedef VipsStartFnFunction =
    ffi.Pointer<ffi.Void> Function(
      ffi.Pointer<VipsImage$1> out,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
    );
typedef VipsStartFnFunction$1 =
    ffi.Pointer<ffi.Void> Function(
      ffi.Pointer<VipsImage> out,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
    );
typedef VipsStopFn = ffi.Pointer<ffi.NativeFunction<VipsStopFnFunction>>;
typedef VipsStopFnFunction =
    ffi.Int Function(
      ffi.Pointer<ffi.Void> seq,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
    );
typedef DartVipsStopFnFunction =
    int Function(
      ffi.Pointer<ffi.Void> seq,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
    );
typedef VipsThing = _VipsThing;
typedef VipsTypeMap2Fn =
    ffi.Pointer<ffi.NativeFunction<VipsTypeMap2FnFunction>>;
typedef VipsTypeMap2FnFunction =
    ffi.Pointer<ffi.Void> Function(
      GType type,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
    );
typedef DartVipsTypeMap2FnFunction =
    ffi.Pointer<ffi.Void> Function(
      Dartgsize type,
      ffi.Pointer<ffi.Void> a,
      ffi.Pointer<ffi.Void> b,
    );
typedef VipsTypeMapFn = ffi.Pointer<ffi.NativeFunction<VipsTypeMapFnFunction>>;
typedef VipsTypeMapFnFunction =
    ffi.Pointer<ffi.Void> Function(GType type, ffi.Pointer<ffi.Void> a);
typedef DartVipsTypeMapFnFunction =
    ffi.Pointer<ffi.Void> Function(Dartgsize type, ffi.Pointer<ffi.Void> a);

final class VipsWindow extends ffi.Struct {
  @ffi.Int()
  external int ref_count;

  external ffi.Pointer<_VipsImage> im;

  @ffi.Int()
  external int top;

  @ffi.Int()
  external int height;

  external ffi.Pointer<VipsPel> data;

  external ffi.Pointer<ffi.Void> baseaddr;

  @ffi.Size()
  external int length;
}

final class _GByteArray extends ffi.Struct {
  external ffi.Pointer<guint8> data;

  @guint()
  external int len;
}

final class _GData extends ffi.Opaque {}

final class _GHashTable extends ffi.Opaque {}

final class _GMutex extends ffi.Union {
  external gpointer p;

  @ffi.Array.multi([2])
  external ffi.Array<guint> i;
}

final class _GObject extends ffi.Struct {
  external GTypeInstance g_type_instance;

  @guint()
  external int ref_count;

  external ffi.Pointer<GData> qdata;
}

/// GObjectClass:
/// @g_type_class: the parent class
/// @constructor: the @constructor function is called by g_object_new () to
/// complete the object initialization after all the construction properties are
/// set. The first thing a @constructor implementation must do is chain up to the
/// @constructor of the parent class. Overriding @constructor should be rarely
/// needed, e.g. to handle construct properties, or to implement singletons.
/// @set_property: the generic setter for all properties of this type. Should be
/// overridden for every type with properties. If implementations of
/// @set_property don't emit property change notification explicitly, this will
/// be done implicitly by the type system. However, if the notify signal is
/// emitted explicitly, the type system will not emit it a second time.
/// @get_property: the generic getter for all properties of this type. Should be
/// overridden for every type with properties.
/// @dispose: the @dispose function is supposed to drop all references to other
/// objects, but keep the instance otherwise intact, so that client method
/// invocations still work. It may be run multiple times (due to reference
/// loops). Before returning, @dispose should chain up to the @dispose method
/// of the parent class.
/// @finalize: instance finalization function, should finish the finalization of
/// the instance begun in @dispose and chain up to the @finalize method of the
/// parent class.
/// @dispatch_properties_changed: emits property change notification for a bunch
/// of properties. Overriding @dispatch_properties_changed should be rarely
/// needed.
/// @notify: the class closure for the notify signal
/// @constructed: the @constructed function is called by g_object_new() as the
/// final step of the object creation process.  At the point of the call, all
/// construction properties have been set on the object.  The purpose of this
/// call is to allow for object initialisation steps that can only be performed
/// after construction properties have been set.  @constructed implementors
/// should chain up to the @constructed call of their parent class to allow it
/// to complete its initialisation.
///
/// The class structure for the GObject type.
///
/// |[<!-- language="C" -->
/// // Example of implementing a singleton using a constructor.
/// static MySingleton *the_singleton = NULL;
///
/// static GObject*
/// my_singleton_constructor (GType                  type,
/// guint                  n_construct_params,
/// GObjectConstructParam *construct_params)
/// {
/// GObject *object;
///
/// if (!the_singleton)
/// {
/// object = G_OBJECT_CLASS (parent_class)->constructor (type,
/// n_construct_params,
/// construct_params);
/// the_singleton = MY_SINGLETON (object);
/// }
/// else
/// object = g_object_ref (G_OBJECT (the_singleton));
///
/// return object;
/// }
/// ]|
final class _GObjectClass extends ffi.Struct {
  external GTypeClass g_type_class;

  external ffi.Pointer<GSList> construct_properties;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<GObject> Function(
        GType type,
        guint n_construct_properties,
        ffi.Pointer<GObjectConstructParam> construct_properties,
      )
    >
  >
  constructor;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<GObject> object,
        guint property_id,
        ffi.Pointer<GValue> value,
        ffi.Pointer<GParamSpec> pspec,
      )
    >
  >
  set_property;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<GObject> object,
        guint property_id,
        ffi.Pointer<GValue> value,
        ffi.Pointer<GParamSpec> pspec,
      )
    >
  >
  get_property;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GObject> object)>
  >
  dispose;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GObject> object)>
  >
  finalize;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<GObject> object,
        guint n_pspecs,
        ffi.Pointer<ffi.Pointer<GParamSpec>> pspecs,
      )
    >
  >
  dispatch_properties_changed;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<GObject> object,
        ffi.Pointer<GParamSpec> pspec,
      )
    >
  >
  notify;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GObject> object)>
  >
  constructed;

  @gsize()
  external int flags;

  @gsize()
  external int n_construct_properties;

  external gpointer pspecs;

  @gsize()
  external int n_pspecs;

  @ffi.Array.multi([3])
  external ffi.Array<gpointer> pdummy;
}

/// GObjectConstructParam:
/// @pspec: the #GParamSpec of the construct parameter
/// @value: the value to set the parameter to
///
/// The GObjectConstructParam struct is an auxiliary structure used to hand
/// #GParamSpec/#GValue pairs to the @constructor of a #GObjectClass.
final class _GObjectConstructParam extends ffi.Struct {
  external ffi.Pointer<GParamSpec> pspec;

  external ffi.Pointer<GValue> value;
}

final class _GParamSpec extends ffi.Struct {
  external GTypeInstance g_type_instance;

  external ffi.Pointer<gchar> name;

  @ffi.Int()
  external int flags;

  @GType()
  external int value_type;

  @GType()
  external int owner_type;

  external ffi.Pointer<gchar> _nick;

  external ffi.Pointer<gchar> _blurb;

  external ffi.Pointer<GData> qdata;

  @guint()
  external int ref_count;

  @guint()
  external int param_id;
}

final class _GSList extends ffi.Struct {
  external gpointer data;

  external ffi.Pointer<GSList$1> next;
}

final class _GThread extends ffi.Struct {
  external GThreadFunc func;

  external gpointer data;

  @gboolean()
  external int joinable;

  @ffi.UnsignedInt()
  external int priorityAsInt;

  GThreadPriority get priority => GThreadPriority.fromValue(priorityAsInt);
}

final class _GTimer extends ffi.Opaque {}

/// GTypeClass:
///
/// An opaque structure used as the base of all classes.
final class _GTypeClass extends ffi.Struct {
  @GType()
  external int g_type;
}

/// GTypeInstance:
///
/// An opaque structure used as the base of all type instances.
final class _GTypeInstance extends ffi.Struct {
  external ffi.Pointer<GTypeClass> g_class;
}

/// GValue:
///
/// An opaque structure used to hold different types of values.
///
/// Before it can be used, a `GValue` has to be initialized to a specific type by
/// calling [method@GObject.Value.init] on it.
///
/// Many types which are stored within a `GValue` need to allocate data on the
/// heap, so [method@GObject.Value.unset] must always be called on a `GValue` to
/// free any such data once you’re finished with the `GValue`, even if the
/// `GValue` itself is stored on the stack.
///
/// The data within the structure has protected scope: it is accessible only
/// to functions within a [struct@GObject.TypeValueTable] structure, or
/// implementations of the `g_value_*()` API. That is, code which implements new
/// fundamental types.
///
/// `GValue` users cannot make any assumptions about how data is stored
/// within the 2 element @data union, and the @g_type member should
/// only be accessed through the [func@GObject.VALUE_TYPE] macro and related
/// macros.
final class _GValue extends ffi.Struct {
  @GType()
  external int g_type;

  @ffi.Array.multi([2])
  external ffi.Array<UnnamedUnion> data;
}

enum _RegionType {
  VIPS_REGION_NONE(0),
  VIPS_REGION_BUFFER(1),
  VIPS_REGION_OTHER_REGION(2),
  VIPS_REGION_OTHER_IMAGE(3),
  VIPS_REGION_WINDOW(4);

  final int value;
  const _RegionType(this.value);

  static _RegionType fromValue(int value) => switch (value) {
    0 => VIPS_REGION_NONE,
    1 => VIPS_REGION_BUFFER,
    2 => VIPS_REGION_OTHER_REGION,
    3 => VIPS_REGION_OTHER_IMAGE,
    4 => VIPS_REGION_WINDOW,
    _ => throw ArgumentError('Unknown value for _RegionType: $value'),
  };
}

final class _VipsArea extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @ffi.Size()
  external int length;

  @ffi.Int()
  external int n;

  @ffi.Int()
  external int count;

  external GMutex lock;

  external VipsCallbackFn free_fn;

  external ffi.Pointer<ffi.Void> client;

  @GType()
  external int type;

  @ffi.Size()
  external int sizeof_type;
}

final class _VipsArgument extends ffi.Struct {
  external ffi.Pointer<GParamSpec> pspec;
}

final class _VipsArgumentClass extends ffi.Struct {
  external VipsArgument parent;

  external ffi.Pointer<VipsObjectClass> object_class;

  @ffi.UnsignedInt()
  external int flagsAsInt;

  VipsArgumentFlags get flags => VipsArgumentFlags.fromValue(flagsAsInt);

  @ffi.Int()
  external int priority;

  @guint()
  external int offset;
}

final class _VipsArgumentInstance extends ffi.Struct {
  external VipsArgument parent;

  external ffi.Pointer<VipsArgumentClass> argument_class;

  external ffi.Pointer<VipsObject> object;

  @gboolean()
  external int assigned;

  @gulong()
  external int close_id;

  @gulong()
  external int invalidate_id;
}

final class _VipsArrayDouble extends ffi.Struct {
  external VipsArea area;
}

final class _VipsArrayImage extends ffi.Struct {
  external VipsArea area;
}

final class _VipsArrayInt extends ffi.Struct {
  external VipsArea area;
}

final class _VipsBlob extends ffi.Struct {
  external VipsArea area;
}

final class _VipsBuf extends ffi.Struct {
  external ffi.Pointer<ffi.Char> base;

  @ffi.Int()
  external int mx;

  @ffi.Int()
  external int i;

  @gboolean()
  external int full;

  @ffi.Int()
  external int lasti;

  @gboolean()
  external int dynamic;
}

final class _VipsBuffer extends ffi.Struct {
  @ffi.Int()
  external int ref_count;

  external ffi.Pointer<_VipsImage> im;

  external VipsRect area;

  @gboolean()
  external int done;

  external ffi.Pointer<VipsBufferCache> cache;

  external ffi.Pointer<VipsPel> buf;

  @ffi.Size()
  external int bsize;
}

final class _VipsBufferCache extends ffi.Struct {
  external ffi.Pointer<GSList> buffers;

  external ffi.Pointer<GThread> thread;

  external ffi.Pointer<_VipsImage> im;

  external ffi.Pointer<VipsBufferThread> buffer_thread;

  external ffi.Pointer<GSList> reserve;

  @ffi.Int()
  external int n_reserve;
}

final class _VipsConnection extends ffi.Struct {
  external VipsObject parent_object;

  @ffi.Int()
  external int descriptor;

  @ffi.Int()
  external int tracked_descriptor;

  @ffi.Int()
  external int close_descriptor;

  external ffi.Pointer<ffi.Char> filename;
}

final class _VipsForeign extends ffi.Struct {
  external VipsOperation parent_object;
}

final class _VipsForeignClass extends ffi.Struct {
  external VipsOperationClass parent_class;

  @ffi.Int()
  external int priority;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> suffs;
}

final class _VipsForeignLoad extends ffi.Struct {
  external VipsForeign parent_object;

  @gboolean()
  external int memory;

  @ffi.UnsignedInt()
  external int accessAsInt;

  VipsAccess get access => VipsAccess.fromValue(accessAsInt);

  @ffi.UnsignedInt()
  external int flagsAsInt;

  VipsForeignFlags get flags => VipsForeignFlags.fromValue(flagsAsInt);

  @ffi.UnsignedInt()
  external int fail_onAsInt;

  VipsFailOn get fail_on => VipsFailOn.fromValue(fail_onAsInt);

  @gboolean()
  external int fail;

  @gboolean()
  external int sequential;

  external ffi.Pointer<VipsImage> out;

  external ffi.Pointer<VipsImage> real;

  @gboolean()
  external int nocache;

  @gboolean()
  external int disc;

  @gboolean()
  external int error;

  @gboolean()
  external int revalidate;
}

final class _VipsForeignLoadClass extends ffi.Struct {
  external VipsForeignClass parent_class;

  external ffi.Pointer<
    ffi.NativeFunction<gboolean Function(ffi.Pointer<ffi.Char> filename)>
  >
  is_a;

  external ffi.Pointer<
    ffi.NativeFunction<
      gboolean Function(ffi.Pointer<ffi.Void> data, ffi.Size size)
    >
  >
  is_a_buffer;

  external ffi.Pointer<
    ffi.NativeFunction<gboolean Function(ffi.Pointer<VipsSource> source)>
  >
  is_a_source;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char> filename)>
  >
  get_flags_filename;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<VipsForeignLoad> load)
    >
  >
  get_flags;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<VipsForeignLoad> load)>
  >
  header;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<VipsForeignLoad> load)>
  >
  load;
}

final class _VipsForeignSave extends ffi.Struct {
  external VipsForeign parent_object;

  @gboolean()
  external int strip;

  @ffi.UnsignedInt()
  external int keepAsInt;

  VipsForeignKeep get keep => VipsForeignKeep.fromValue(keepAsInt);

  external ffi.Pointer<ffi.Char> profile;

  external ffi.Pointer<VipsArrayDouble> background;

  @ffi.Int()
  external int page_height;

  external ffi.Pointer<VipsImage> in$;

  external ffi.Pointer<VipsImage> ready;
}

final class _VipsForeignSaveClass extends ffi.Struct {
  external VipsForeignClass parent_class;

  @ffi.UnsignedInt()
  external int saveableAsInt;

  VipsForeignSaveable get saveable =>
      VipsForeignSaveable.fromValue(saveableAsInt);

  external ffi.Pointer<ffi.Int> format_table;

  @ffi.UnsignedInt()
  external int codingAsInt;

  VipsForeignCoding get coding => VipsForeignCoding.fromValue(codingAsInt);
}

final class _VipsImage extends ffi.Struct {
  external VipsObject parent_instance;

  @ffi.Int()
  external int Xsize;

  @ffi.Int()
  external int Ysize;

  @ffi.Int()
  external int Bands;

  @ffi.Int()
  external int BandFmtAsInt;

  VipsBandFormat get BandFmt => VipsBandFormat.fromValue(BandFmtAsInt);

  @ffi.Int()
  external int CodingAsInt;

  VipsCoding get Coding => VipsCoding.fromValue(CodingAsInt);

  @ffi.Int()
  external int TypeAsInt;

  VipsInterpretation get Type => VipsInterpretation.fromValue(TypeAsInt);

  @ffi.Double()
  external double Xres;

  @ffi.Double()
  external double Yres;

  @ffi.Int()
  external int Xoffset;

  @ffi.Int()
  external int Yoffset;

  @ffi.Int()
  external int Length;

  @ffi.Short()
  external int Compression;

  @ffi.Short()
  external int Level;

  @ffi.Int()
  external int Bbits;

  external ffi.Pointer<VipsProgress> time;

  external ffi.Pointer<ffi.Char> Hist;

  external ffi.Pointer<ffi.Char> filename;

  external ffi.Pointer<VipsPel> data;

  @ffi.Int()
  external int kill;

  @ffi.Float()
  external double Xres_float;

  @ffi.Float()
  external double Yres_float;

  external ffi.Pointer<ffi.Char> mode;

  @ffi.Int()
  external int dtypeAsInt;

  VipsImageType get dtype => VipsImageType.fromValue(dtypeAsInt);

  @ffi.Int()
  external int fd;

  external ffi.Pointer<ffi.Void> baseaddr;

  @ffi.Size()
  external int length;

  @guint32()
  external int magic;

  external VipsStartFn start_fn;

  external VipsGenerateFn generate_fn;

  external VipsStopFn stop_fn;

  external ffi.Pointer<ffi.Void> client1;

  external ffi.Pointer<ffi.Void> client2;

  external GMutex sslock;

  external ffi.Pointer<GSList> regions;

  @ffi.Int()
  external int dhintAsInt;

  VipsDemandStyle get dhint => VipsDemandStyle.fromValue(dhintAsInt);

  external ffi.Pointer<GHashTable> meta;

  external ffi.Pointer<GSList> meta_traverse;

  @gint64()
  external int sizeof_header;

  external ffi.Pointer<GSList> windows;

  external ffi.Pointer<GSList> upstream;

  external ffi.Pointer<GSList> downstream;

  @ffi.Int()
  external int serial;

  external ffi.Pointer<GSList> history_list;

  external ffi.Pointer<VipsImage$1> progress_signal;

  @gint64()
  external int file_length;

  @gboolean()
  external int hint_set;

  @gboolean()
  external int delete_on_close;

  external ffi.Pointer<ffi.Char> delete_on_close_filename;
}

final class _VipsImageClass extends ffi.Struct {
  external VipsObjectClass parent_class;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<VipsImage> image,
        ffi.Pointer<VipsProgress> progress,
        ffi.Pointer<ffi.Void> data,
      )
    >
  >
  preeval;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<VipsImage> image,
        ffi.Pointer<VipsProgress> progress,
        ffi.Pointer<ffi.Void> data,
      )
    >
  >
  eval;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<VipsImage> image,
        ffi.Pointer<VipsProgress> progress,
        ffi.Pointer<ffi.Void> data,
      )
    >
  >
  posteval;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<VipsImage> image,
        ffi.Pointer<ffi.Int> result,
        ffi.Pointer<ffi.Void> data,
      )
    >
  >
  written;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<VipsImage> image,
        ffi.Pointer<ffi.Void> data,
      )
    >
  >
  invalidate;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<VipsImage> image,
        ffi.Pointer<ffi.Void> data,
      )
    >
  >
  minimise;
}

final class _VipsObject extends ffi.Struct {
  external GObject parent_instance;

  @gboolean()
  external int constructed;

  @gboolean()
  external int static_object;

  external ffi.Pointer<VipsArgumentTable> argument_table;

  external ffi.Pointer<ffi.Char> nickname;

  external ffi.Pointer<ffi.Char> description;

  @gboolean()
  external int preclose;

  @gboolean()
  external int close;

  @gboolean()
  external int postclose;

  @ffi.Size()
  external int local_memory;
}

final class _VipsObjectClass extends ffi.Struct {
  external GObjectClass parent_class;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<VipsObject> object)>
  >
  build;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<VipsObject> object,
        ffi.Pointer<ffi.Void> data,
      )
    >
  >
  postbuild;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<_VipsObjectClass> cls,
        ffi.Pointer<VipsBuf> buf,
      )
    >
  >
  summary_class;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<VipsObject> object,
        ffi.Pointer<VipsBuf> buf,
      )
    >
  >
  summary;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<VipsObject> object,
        ffi.Pointer<VipsBuf> buf,
      )
    >
  >
  dump;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<VipsObject> object,
        ffi.Pointer<VipsBuf> buf,
      )
    >
  >
  sanity;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VipsObject> object)>
  >
  rewind;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VipsObject> object)>
  >
  preclose;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VipsObject> object)>
  >
  close;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VipsObject> object)>
  >
  postclose;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<VipsObject> Function(ffi.Pointer<ffi.Char> string)
    >
  >
  new_from_string;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<VipsObject> object,
        ffi.Pointer<VipsBuf> buf,
      )
    >
  >
  to_string;

  @gboolean()
  external int output_needs_arg;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<VipsObject> object,
        ffi.Pointer<ffi.Char> string,
      )
    >
  >
  output_to_arg;

  external ffi.Pointer<ffi.Char> nickname;

  external ffi.Pointer<ffi.Char> description;

  external ffi.Pointer<VipsArgumentTable> argument_table;

  external ffi.Pointer<GSList> argument_table_traverse;

  @GType()
  external int argument_table_traverse_gtype;

  @gboolean()
  external int deprecated;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _vips_reserved1;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _vips_reserved2;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _vips_reserved3;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _vips_reserved4;
}

final class _VipsOperation extends ffi.Struct {
  external VipsObject parent_instance;

  @guint()
  external int hash;

  @gboolean()
  external int found_hash;

  @ffi.Int()
  external int pixels;
}

final class _VipsOperationClass extends ffi.Struct {
  external VipsObjectClass parent_class;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<_VipsOperationClass> cls,
        ffi.Pointer<VipsBuf> buf,
      )
    >
  >
  usage;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<VipsOperation> operation)
    >
  >
  get_flags;

  @ffi.UnsignedInt()
  external int flagsAsInt;

  VipsOperationFlags get flags => VipsOperationFlags.fromValue(flagsAsInt);

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VipsOperation> operation)>
  >
  invalidate;
}

final class _VipsProgress extends ffi.Struct {
  external ffi.Pointer<VipsImage$1> im;

  @ffi.Int()
  external int run;

  @ffi.Int()
  external int eta;

  @gint64()
  external int tpels;

  @gint64()
  external int npels;

  @ffi.Int()
  external int percent;

  external ffi.Pointer<GTimer> start;
}

final class _VipsRect extends ffi.Struct {
  @ffi.Int()
  external int left;

  @ffi.Int()
  external int top;

  @ffi.Int()
  external int width;

  @ffi.Int()
  external int height;
}

final class _VipsRefString extends ffi.Struct {
  external VipsArea area;
}

final class _VipsRegion extends ffi.Struct {
  external VipsObject parent_object;

  external ffi.Pointer<VipsImage$1> im;

  external VipsRect valid;

  @ffi.UnsignedInt()
  external int typeAsInt;

  _RegionType get type => _RegionType.fromValue(typeAsInt);

  external ffi.Pointer<VipsPel> data;

  @ffi.Int()
  external int bpl;

  external ffi.Pointer<ffi.Void> seq;

  external ffi.Pointer<GThread> thread;

  external ffi.Pointer<VipsWindow> window;

  external ffi.Pointer<VipsBuffer> buffer;

  @gboolean()
  external int invalid;
}

final class _VipsSaveString extends ffi.Struct {
  external ffi.Pointer<ffi.Char> s;
}

final class _VipsSource extends ffi.Struct {
  external VipsConnection parent_object;

  @gboolean()
  external int decode;

  @gboolean()
  external int have_tested_seek;

  @gboolean()
  external int is_pipe;

  @gint64()
  external int read_position;

  @gint64()
  external int length;

  external ffi.Pointer<ffi.Void> data;

  external ffi.Pointer<GByteArray> header_bytes;

  external ffi.Pointer<GByteArray> sniff;

  external ffi.Pointer<VipsBlob> blob;

  external ffi.Pointer<ffi.Void> mmap_baseaddr;

  @ffi.Size()
  external int mmap_length;
}

final class _VipsThing extends ffi.Struct {
  @ffi.Int()
  external int i;
}

typedef gboolean = gint;
typedef gchar = ffi.Char;
typedef Dartgchar = int;
typedef gdouble = ffi.Double;
typedef Dartgdouble = double;
typedef gfloat = ffi.Float;
typedef Dartgfloat = double;
typedef gint = ffi.Int;
typedef Dartgint = int;
typedef gint64 = ffi.LongLong;
typedef Dartgint64 = int;
typedef glong = ffi.Long;
typedef Dartglong = int;
typedef gpointer = ffi.Pointer<ffi.Void>;
typedef gsize = ffi.UnsignedLong;
typedef Dartgsize = int;
typedef guint = ffi.UnsignedInt;
typedef Dartguint = int;
typedef guint32 = ffi.UnsignedInt;
typedef Dartguint32 = int;
typedef guint64 = ffi.UnsignedLongLong;
typedef Dartguint64 = int;
typedef guint8 = ffi.UnsignedChar;
typedef Dartguint8 = int;
typedef gulong = ffi.UnsignedLong;
typedef Dartgulong = int;
